import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${montserrat.className} antialiased container`}>
                <header>
                    <Navbar />
                </header>
                {children}
                <footer>
                    <p>estes el el footer</p>
                </footer>
            </body>
        </html>
    );
}
